before_install:
    # init xvfb
    # http://docs.travis-ci.com/user/gui-and-headless-browsers/
    - export DISPLAY=:99.0 && sh -e /etc/init.d/xvfb start
branches:
    only:
    - alpha
    - beta
    - cron
    - docker.base
    - docker.latest
    - master
    - publish
    - task
env:
    global:
    # this value is auto-created by shTravisCryptoAesEncryptYml
    - secure: EMfeo7praYpU5NjOtEWtb0rqXmdblqUKxo2Iuf+zjkCdcn2iHsSAY9iu+wRWCcBxUSBu8xFEB+0AfLHtwRXaBzX6k/nNYJ0TLASO7pys9Lx+an5rWKQWeQvpSP6HUYQXDcwHXy7SGJHiIGRiLmv6o2l34Gs1Nnxwzl0oDVK+IlVenCj/Rha8W01T2pmmPAkROQD0dLbSr7C0e36uo7QClQsPWviqRMp17m6DIrGcSgzkuvgKskK7vJA9IOavr97EXdS/L16Fl90u3/lGBcJnvxr1jRC9bUcNf24q3Wnv8HYm4iBd9WKLW5UO+MtIpzElUcfXKVdC7oW/iuVXyP86yropaLlMKpBiqQXvknJJk7H7wk5nMBRAYFqnIMcZkw4dShJwoBkv74aglyIBZddjtYqVwgxlWNPHxv0kGg/e5NPJT1cOMBDyfWMcWnP/TO8tP1sbH7gTM0gylpD2acfd/SUtjPLvclzGU9T+jVfvCmvpxO4k2EphQ2HZiHIcPbjA4Vnm5qrBoHBZxg6qaTW81Sx3xdK9o+FcabR8C4U4obtg1lvod5bUT85gl7HrUFaQeF33+LTEmSi02Ahy1Z6If1JsPHeNxhN1xGmDPq/1oRLRBDXJ5GL4ESjE7UJdX9Kun+571wcjcy5+h4L2ldtuqt0oOnWRaOmN5X71wCaoqms= # CRYPTO_AES_KEY
    # this value is auto-created by shTravisCryptoAesEncryptYml

language:
    - node_js
node_js:
    - 6
    # - node
script:
    - npm run build-ci
services:
    - docker
# http://docs.travis-ci.com/user/workers/container-based-infrastructure
sudo:
    false
